# Generated by Django 4.2.20 on 2025-03-07 22:36

from django.db import migrations, models
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.models.get_file_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('hash_type', models.CharField(choices=[('blake3', 'Blake3'), ('md5', 'MD5'), ('sha256', 'SHA256')], default='blake3', max_length=10)),
                ('file_hash', models.CharField(db_index=True, max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
